; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch64 < %s | FileCheck %s

define i8 @atomicrmw_xchg_i8_acquire(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i8_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB0_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB0_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 %b acquire
  ret i8 %1
}

define i8 @atomicrmw_xchg_0_i8_acquire(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_0_i8_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r5, $zero, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB1_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB1_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 0 acquire
  ret i8 %1
}

define i8 @atomicrmw_xchg_minus_1_i8_acquire(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_minus_1_i8_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r5, $zero, -1
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB2_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB2_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 -1 acquire
  ret i8 %1
}

define i16 @atomicrmw_xchg_i16_acquire(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i16_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB3_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB3_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 %b acquire
  ret i16 %1
}

define i16 @atomicrmw_xchg_0_i16_acquire(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_0_i16_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r5, $zero, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB4_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB4_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 0 acquire
  ret i16 %1
}

define i16 @atomicrmw_xchg_minus_1_i16_acquire(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_minus_1_i16_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r5, $zero, -1
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB5_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB5_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 -1 acquire
  ret i16 %1
}

define i32 @atomicrmw_xchg_i32_acquire(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i32_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amswap_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i32 %b acquire
  ret i32 %1
}

define i64 @atomicrmw_xchg_i64_acquire(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i64_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amswap_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i64 %b acquire
  ret i64 %1
}

define i8 @atomicrmw_add_i8_acquire(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i8_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB8_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    add.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB8_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i8 %b acquire
  ret i8 %1
}

define i16 @atomicrmw_add_i16_acquire(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i16_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB9_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    add.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB9_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i16 %b acquire
  ret i16 %1
}

define i32 @atomicrmw_add_i32_acquire(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i32_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amadd_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i32 %b acquire
  ret i32 %1
}

define i64 @atomicrmw_add_i64_acquire(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i64_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amadd_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i64 %b acquire
  ret i64 %1
}

define i8 @atomicrmw_sub_i8_acquire(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i8_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB12_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    sub.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB12_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i8 %b acquire
  ret i8 %1
}

define i16 @atomicrmw_sub_i16_acquire(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i16_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB13_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    sub.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB13_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i16 %b acquire
  ret i16 %1
}

define i32 @atomicrmw_sub_i32_acquire(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i32_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sub.w $r7, $zero, $r6
; CHECK-NEXT:    amadd_db.w $r5, $r7, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i32 %b acquire
  ret i32 %1
}

define i64 @atomicrmw_sub_i64_acquire(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i64_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sub.d $r7, $zero, $r5
; CHECK-NEXT:    amadd_db.d $r6, $r7, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i64 %b acquire
  ret i64 %1
}

define i8 @atomicrmw_nand_i8_acquire(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i8_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB16_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    nor $r11, $zero, $r11
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB16_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i8 %b acquire
  ret i8 %1
}

define i16 @atomicrmw_nand_i16_acquire(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i16_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB17_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    nor $r11, $zero, $r11
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB17_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i16 %b acquire
  ret i16 %1
}

define i32 @atomicrmw_nand_i32_acquire(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i32_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  .LBB18_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r5, $r4, 0
; CHECK-NEXT:    and $r7, $r5, $r6
; CHECK-NEXT:    nor $r7, $zero, $r7
; CHECK-NEXT:    sc.w $r7, $r4, 0
; CHECK-NEXT:    beq $r7, $zero, .LBB18_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i32 %b acquire
  ret i32 %1
}

define i64 @atomicrmw_nand_i64_acquire(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i64_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:  .LBB19_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.d $r6, $r4, 0
; CHECK-NEXT:    and $r7, $r6, $r5
; CHECK-NEXT:    nor $r7, $zero, $r7
; CHECK-NEXT:    sc.d $r7, $r4, 0
; CHECK-NEXT:    beq $r7, $zero, .LBB19_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i64 %b acquire
  ret i64 %1
}

define i8 @atomicrmw_and_i8_acquire(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i8_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB20_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB20_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i8 %b acquire
  ret i8 %1
}

define i16 @atomicrmw_and_i16_acquire(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i16_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB21_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB21_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i16 %b acquire
  ret i16 %1
}

define i32 @atomicrmw_and_i32_acquire(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i32_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amand_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i32 %b acquire
  ret i32 %1
}

define i64 @atomicrmw_and_i64_acquire(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i64_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amand_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i64 %b acquire
  ret i64 %1
}

define i8 @atomicrmw_or_i8_acquire(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i8_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB24_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    or $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB24_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i8 %b acquire
  ret i8 %1
}

define i16 @atomicrmw_or_i16_acquire(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i16_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB25_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    or $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB25_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i16 %b acquire
  ret i16 %1
}

define i32 @atomicrmw_or_i32_acquire(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i32_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amor_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i32 %b acquire
  ret i32 %1
}

define i64 @atomicrmw_or_i64_acquire(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i64_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amor_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i64 %b acquire
  ret i64 %1
}

define i8 @atomicrmw_xor_i8_acquire(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i8_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB28_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    xor $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB28_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i8 %b acquire
  ret i8 %1
}

define i16 @atomicrmw_xor_i16_acquire(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i16_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB29_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    xor $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB29_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i16 %b acquire
  ret i16 %1
}

define i32 @atomicrmw_xor_i32_acquire(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i32_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amxor_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i32 %b acquire
  ret i32 %1
}

define i64 @atomicrmw_xor_i64_acquire(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i64_acquire:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amxor_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i64 %b acquire
  ret i64 %1
}

define i8 @atomicrmw_xchg_i8_release(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i8_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB32_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB32_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 %b release
  ret i8 %1
}

define i8 @atomicrmw_xchg_0_i8_release(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_0_i8_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r5, $zero, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB33_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB33_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 0 release
  ret i8 %1
}

define i8 @atomicrmw_xchg_minus_1_i8_release(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_minus_1_i8_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r5, $zero, -1
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB34_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB34_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 -1 release
  ret i8 %1
}

define i16 @atomicrmw_xchg_i16_release(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i16_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB35_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB35_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 %b release
  ret i16 %1
}

define i16 @atomicrmw_xchg_0_i16_release(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_0_i16_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r5, $zero, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB36_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB36_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 0 release
  ret i16 %1
}

define i16 @atomicrmw_xchg_minus_1_i16_release(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_minus_1_i16_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r5, $zero, -1
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB37_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB37_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 -1 release
  ret i16 %1
}

define i32 @atomicrmw_xchg_i32_release(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i32_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amswap_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i32 %b release
  ret i32 %1
}

define i64 @atomicrmw_xchg_i64_release(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i64_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amswap_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i64 %b release
  ret i64 %1
}

define i8 @atomicrmw_add_i8_release(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i8_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB40_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    add.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB40_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i8 %b release
  ret i8 %1
}

define i16 @atomicrmw_add_i16_release(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i16_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB41_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    add.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB41_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i16 %b release
  ret i16 %1
}

define i32 @atomicrmw_add_i32_release(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i32_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amadd_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i32 %b release
  ret i32 %1
}

define i64 @atomicrmw_add_i64_release(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i64_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amadd_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i64 %b release
  ret i64 %1
}

define i8 @atomicrmw_sub_i8_release(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i8_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB44_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    sub.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB44_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i8 %b release
  ret i8 %1
}

define i16 @atomicrmw_sub_i16_release(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i16_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB45_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    sub.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB45_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i16 %b release
  ret i16 %1
}

define i32 @atomicrmw_sub_i32_release(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i32_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sub.w $r7, $zero, $r6
; CHECK-NEXT:    amadd_db.w $r5, $r7, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i32 %b release
  ret i32 %1
}

define i64 @atomicrmw_sub_i64_release(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i64_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sub.d $r7, $zero, $r5
; CHECK-NEXT:    amadd_db.d $r6, $r7, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i64 %b release
  ret i64 %1
}

define i8 @atomicrmw_nand_i8_release(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i8_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB48_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    nor $r11, $zero, $r11
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB48_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i8 %b release
  ret i8 %1
}

define i16 @atomicrmw_nand_i16_release(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i16_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB49_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    nor $r11, $zero, $r11
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB49_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i16 %b release
  ret i16 %1
}

define i32 @atomicrmw_nand_i32_release(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i32_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  .LBB50_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r5, $r4, 0
; CHECK-NEXT:    and $r7, $r5, $r6
; CHECK-NEXT:    nor $r7, $zero, $r7
; CHECK-NEXT:    sc.w $r7, $r4, 0
; CHECK-NEXT:    beq $r7, $zero, .LBB50_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i32 %b release
  ret i32 %1
}

define i64 @atomicrmw_nand_i64_release(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i64_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:  .LBB51_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.d $r6, $r4, 0
; CHECK-NEXT:    and $r7, $r6, $r5
; CHECK-NEXT:    nor $r7, $zero, $r7
; CHECK-NEXT:    sc.d $r7, $r4, 0
; CHECK-NEXT:    beq $r7, $zero, .LBB51_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i64 %b release
  ret i64 %1
}

define i8 @atomicrmw_and_i8_release(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i8_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB52_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB52_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i8 %b release
  ret i8 %1
}

define i16 @atomicrmw_and_i16_release(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i16_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB53_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB53_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i16 %b release
  ret i16 %1
}

define i32 @atomicrmw_and_i32_release(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i32_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amand_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i32 %b release
  ret i32 %1
}

define i64 @atomicrmw_and_i64_release(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i64_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amand_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i64 %b release
  ret i64 %1
}

define i8 @atomicrmw_or_i8_release(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i8_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB56_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    or $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB56_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i8 %b release
  ret i8 %1
}

define i16 @atomicrmw_or_i16_release(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i16_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB57_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    or $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB57_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i16 %b release
  ret i16 %1
}

define i32 @atomicrmw_or_i32_release(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i32_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amor_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i32 %b release
  ret i32 %1
}

define i64 @atomicrmw_or_i64_release(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i64_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amor_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i64 %b release
  ret i64 %1
}

define i8 @atomicrmw_xor_i8_release(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i8_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB60_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    xor $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB60_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i8 %b release
  ret i8 %1
}

define i16 @atomicrmw_xor_i16_release(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i16_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB61_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    xor $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB61_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i16 %b release
  ret i16 %1
}

define i32 @atomicrmw_xor_i32_release(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i32_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amxor_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i32 %b release
  ret i32 %1
}

define i64 @atomicrmw_xor_i64_release(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i64_release:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amxor_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i64 %b release
  ret i64 %1
}

define i8 @atomicrmw_xchg_i8_acq_rel(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i8_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB64_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB64_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i8 @atomicrmw_xchg_0_i8_acq_rel(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_0_i8_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r5, $zero, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB65_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB65_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 0 acq_rel
  ret i8 %1
}

define i8 @atomicrmw_xchg_minus_1_i8_acq_rel(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_minus_1_i8_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r5, $zero, -1
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB66_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB66_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 -1 acq_rel
  ret i8 %1
}

define i16 @atomicrmw_xchg_i16_acq_rel(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i16_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB67_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB67_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i16 @atomicrmw_xchg_0_i16_acq_rel(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_0_i16_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r5, $zero, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB68_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB68_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 0 acq_rel
  ret i16 %1
}

define i16 @atomicrmw_xchg_minus_1_i16_acq_rel(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_minus_1_i16_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r5, $zero, -1
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB69_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB69_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 -1 acq_rel
  ret i16 %1
}

define i32 @atomicrmw_xchg_i32_acq_rel(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i32_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amswap_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i64 @atomicrmw_xchg_i64_acq_rel(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i64_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amswap_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i8 @atomicrmw_add_i8_acq_rel(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i8_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB72_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    add.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB72_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i16 @atomicrmw_add_i16_acq_rel(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i16_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB73_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    add.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB73_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i32 @atomicrmw_add_i32_acq_rel(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i32_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amadd_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i64 @atomicrmw_add_i64_acq_rel(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i64_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amadd_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i8 @atomicrmw_sub_i8_acq_rel(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i8_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB76_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    sub.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB76_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i16 @atomicrmw_sub_i16_acq_rel(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i16_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB77_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    sub.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB77_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i32 @atomicrmw_sub_i32_acq_rel(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i32_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sub.w $r7, $zero, $r6
; CHECK-NEXT:    amadd_db.w $r5, $r7, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i64 @atomicrmw_sub_i64_acq_rel(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i64_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sub.d $r7, $zero, $r5
; CHECK-NEXT:    amadd_db.d $r6, $r7, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i8 @atomicrmw_nand_i8_acq_rel(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i8_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB80_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    nor $r11, $zero, $r11
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB80_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i16 @atomicrmw_nand_i16_acq_rel(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i16_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB81_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    nor $r11, $zero, $r11
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB81_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i32 @atomicrmw_nand_i32_acq_rel(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i32_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  .LBB82_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r5, $r4, 0
; CHECK-NEXT:    and $r7, $r5, $r6
; CHECK-NEXT:    nor $r7, $zero, $r7
; CHECK-NEXT:    sc.w $r7, $r4, 0
; CHECK-NEXT:    beq $r7, $zero, .LBB82_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i64 @atomicrmw_nand_i64_acq_rel(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i64_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:  .LBB83_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.d $r6, $r4, 0
; CHECK-NEXT:    and $r7, $r6, $r5
; CHECK-NEXT:    nor $r7, $zero, $r7
; CHECK-NEXT:    sc.d $r7, $r4, 0
; CHECK-NEXT:    beq $r7, $zero, .LBB83_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i8 @atomicrmw_and_i8_acq_rel(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i8_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB84_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB84_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i16 @atomicrmw_and_i16_acq_rel(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i16_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB85_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB85_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i32 @atomicrmw_and_i32_acq_rel(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i32_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amand_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i64 @atomicrmw_and_i64_acq_rel(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i64_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amand_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i8 @atomicrmw_or_i8_acq_rel(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i8_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB88_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    or $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB88_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i16 @atomicrmw_or_i16_acq_rel(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i16_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB89_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    or $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB89_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i32 @atomicrmw_or_i32_acq_rel(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i32_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amor_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i64 @atomicrmw_or_i64_acq_rel(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i64_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amor_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i8 @atomicrmw_xor_i8_acq_rel(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i8_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB92_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    xor $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB92_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i8 %b acq_rel
  ret i8 %1
}

define i16 @atomicrmw_xor_i16_acq_rel(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i16_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB93_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    xor $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB93_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i16 %b acq_rel
  ret i16 %1
}

define i32 @atomicrmw_xor_i32_acq_rel(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i32_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amxor_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i32 %b acq_rel
  ret i32 %1
}

define i64 @atomicrmw_xor_i64_acq_rel(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i64_acq_rel:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amxor_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i64 %b acq_rel
  ret i64 %1
}

define i8 @atomicrmw_xchg_i8_seq_cst(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i8_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB96_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB96_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i8 @atomicrmw_xchg_0_i8_seq_cst(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_0_i8_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r5, $zero, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB97_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB97_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 0 seq_cst
  ret i8 %1
}

define i8 @atomicrmw_xchg_minus_1_i8_seq_cst(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_minus_1_i8_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r5, $zero, -1
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB98_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB98_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 -1 seq_cst
  ret i8 %1
}

define i16 @atomicrmw_xchg_i16_seq_cst(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i16_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB99_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB99_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i16 @atomicrmw_xchg_0_i16_seq_cst(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_0_i16_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r5, $zero, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB100_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB100_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 0 seq_cst
  ret i16 %1
}

define i16 @atomicrmw_xchg_minus_1_i16_seq_cst(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_minus_1_i16_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r5, $zero, -1
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB101_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB101_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 -1 seq_cst
  ret i16 %1
}

define i32 @atomicrmw_xchg_i32_seq_cst(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i32_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amswap_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i64 @atomicrmw_xchg_i64_seq_cst(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i64_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amswap_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i8 @atomicrmw_add_i8_seq_cst(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i8_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB104_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    add.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB104_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i16 @atomicrmw_add_i16_seq_cst(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i16_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB105_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    add.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB105_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i32 @atomicrmw_add_i32_seq_cst(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i32_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amadd_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i64 @atomicrmw_add_i64_seq_cst(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i64_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amadd_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i8 @atomicrmw_sub_i8_seq_cst(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i8_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB108_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    sub.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB108_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i16 @atomicrmw_sub_i16_seq_cst(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i16_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB109_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    sub.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB109_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i32 @atomicrmw_sub_i32_seq_cst(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i32_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sub.w $r7, $zero, $r6
; CHECK-NEXT:    amadd_db.w $r5, $r7, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i64 @atomicrmw_sub_i64_seq_cst(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i64_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sub.d $r7, $zero, $r5
; CHECK-NEXT:    amadd_db.d $r6, $r7, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i8 @atomicrmw_nand_i8_seq_cst(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i8_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB112_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    nor $r11, $zero, $r11
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB112_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i16 @atomicrmw_nand_i16_seq_cst(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i16_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB113_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    nor $r11, $zero, $r11
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB113_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i32 @atomicrmw_nand_i32_seq_cst(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i32_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  .LBB114_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r5, $r4, 0
; CHECK-NEXT:    and $r7, $r5, $r6
; CHECK-NEXT:    nor $r7, $zero, $r7
; CHECK-NEXT:    sc.w $r7, $r4, 0
; CHECK-NEXT:    beq $r7, $zero, .LBB114_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i64 @atomicrmw_nand_i64_seq_cst(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i64_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:  .LBB115_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.d $r6, $r4, 0
; CHECK-NEXT:    and $r7, $r6, $r5
; CHECK-NEXT:    nor $r7, $zero, $r7
; CHECK-NEXT:    sc.d $r7, $r4, 0
; CHECK-NEXT:    beq $r7, $zero, .LBB115_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i8 @atomicrmw_and_i8_seq_cst(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i8_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB116_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB116_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i16 @atomicrmw_and_i16_seq_cst(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i16_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB117_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB117_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i32 @atomicrmw_and_i32_seq_cst(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i32_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amand_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i64 @atomicrmw_and_i64_seq_cst(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i64_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amand_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i8 @atomicrmw_or_i8_seq_cst(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i8_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB120_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    or $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB120_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i16 @atomicrmw_or_i16_seq_cst(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i16_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB121_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    or $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB121_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i32 @atomicrmw_or_i32_seq_cst(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i32_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amor_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i64 @atomicrmw_or_i64_seq_cst(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i64_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amor_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i8 @atomicrmw_xor_i8_seq_cst(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i8_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB124_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    xor $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB124_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i8 %b seq_cst
  ret i8 %1
}

define i16 @atomicrmw_xor_i16_seq_cst(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i16_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB125_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    xor $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB125_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i16 %b seq_cst
  ret i16 %1
}

define i32 @atomicrmw_xor_i32_seq_cst(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i32_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amxor_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i32 %b seq_cst
  ret i32 %1
}

define i64 @atomicrmw_xor_i64_seq_cst(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i64_seq_cst:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amxor_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i64 %b seq_cst
  ret i64 %1
}

define i8 @atomicrmw_xchg_i8_monotonic(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i8_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB128_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB128_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 %b monotonic
  ret i8 %1
}

define i8 @atomicrmw_xchg_0_i8_monotonic(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_0_i8_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r5, $zero, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB129_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB129_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 0 monotonic
  ret i8 %1
}

define i8 @atomicrmw_xchg_minus_1_i8_monotonic(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_minus_1_i8_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r5, $zero, -1
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB130_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB130_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i8 -1 monotonic
  ret i8 %1
}

define i16 @atomicrmw_xchg_i16_monotonic(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i16_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB131_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB131_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 %b monotonic
  ret i16 %1
}

define i16 @atomicrmw_xchg_0_i16_monotonic(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_0_i16_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r5, $zero, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB132_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB132_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 0 monotonic
  ret i16 %1
}

define i16 @atomicrmw_xchg_minus_1_i16_monotonic(ptr %a) nounwind {
; CHECK-LABEL: atomicrmw_xchg_minus_1_i16_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r5, $zero, -1
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB133_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r5, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB133_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i16 -1 monotonic
  ret i16 %1
}

define i32 @atomicrmw_xchg_i32_monotonic(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i32_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amswap_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i32 %b monotonic
  ret i32 %1
}

define i64 @atomicrmw_xchg_i64_monotonic(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_xchg_i64_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amswap_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xchg ptr %a, i64 %b monotonic
  ret i64 %1
}

define i8 @atomicrmw_add_i8_monotonic(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i8_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB136_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    add.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB136_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i8 %b monotonic
  ret i8 %1
}

define i16 @atomicrmw_add_i16_monotonic(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i16_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB137_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    add.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB137_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i16 %b monotonic
  ret i16 %1
}

define i32 @atomicrmw_add_i32_monotonic(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i32_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amadd_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i32 %b monotonic
  ret i32 %1
}

define i64 @atomicrmw_add_i64_monotonic(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_add_i64_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amadd_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw add ptr %a, i64 %b monotonic
  ret i64 %1
}

define i8 @atomicrmw_sub_i8_monotonic(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i8_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB140_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    sub.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB140_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i8 %b monotonic
  ret i8 %1
}

define i16 @atomicrmw_sub_i16_monotonic(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i16_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB141_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    sub.w $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB141_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i16 %b monotonic
  ret i16 %1
}

define i32 @atomicrmw_sub_i32_monotonic(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i32_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sub.w $r7, $zero, $r6
; CHECK-NEXT:    amadd_db.w $r5, $r7, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i32 %b monotonic
  ret i32 %1
}

define i64 @atomicrmw_sub_i64_monotonic(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_sub_i64_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    sub.d $r7, $zero, $r5
; CHECK-NEXT:    amadd_db.d $r6, $r7, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw sub ptr %a, i64 %b monotonic
  ret i64 %1
}

define i8 @atomicrmw_nand_i8_monotonic(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i8_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB144_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    nor $r11, $zero, $r11
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB144_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i8 %b monotonic
  ret i8 %1
}

define i16 @atomicrmw_nand_i16_monotonic(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i16_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB145_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    nor $r11, $zero, $r11
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB145_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i16 %b monotonic
  ret i16 %1
}

define i32 @atomicrmw_nand_i32_monotonic(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i32_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  .LBB146_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r5, $r4, 0
; CHECK-NEXT:    and $r7, $r5, $r6
; CHECK-NEXT:    nor $r7, $zero, $r7
; CHECK-NEXT:    sc.w $r7, $r4, 0
; CHECK-NEXT:    beq $r7, $zero, .LBB146_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i32 %b monotonic
  ret i32 %1
}

define i64 @atomicrmw_nand_i64_monotonic(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_nand_i64_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:  .LBB147_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.d $r6, $r4, 0
; CHECK-NEXT:    and $r7, $r6, $r5
; CHECK-NEXT:    nor $r7, $zero, $r7
; CHECK-NEXT:    sc.d $r7, $r4, 0
; CHECK-NEXT:    beq $r7, $zero, .LBB147_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw nand ptr %a, i64 %b monotonic
  ret i64 %1
}

define i8 @atomicrmw_and_i8_monotonic(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i8_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB148_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB148_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i8 %b monotonic
  ret i8 %1
}

define i16 @atomicrmw_and_i16_monotonic(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i16_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB149_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    and $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB149_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i16 %b monotonic
  ret i16 %1
}

define i32 @atomicrmw_and_i32_monotonic(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i32_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amand_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i32 %b monotonic
  ret i32 %1
}

define i64 @atomicrmw_and_i64_monotonic(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_and_i64_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amand_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw and ptr %a, i64 %b monotonic
  ret i64 %1
}

define i8 @atomicrmw_or_i8_monotonic(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i8_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB152_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    or $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB152_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i8 %b monotonic
  ret i8 %1
}

define i16 @atomicrmw_or_i16_monotonic(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i16_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB153_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    or $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB153_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i16 %b monotonic
  ret i16 %1
}

define i32 @atomicrmw_or_i32_monotonic(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i32_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amor_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i32 %b monotonic
  ret i32 %1
}

define i64 @atomicrmw_or_i64_monotonic(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_or_i64_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amor_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw or ptr %a, i64 %b monotonic
  ret i64 %1
}

define i8 @atomicrmw_xor_i8_monotonic(ptr %a, i8 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i8_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    ori $r4, $zero, 255
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB156_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    xor $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB156_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.b $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i8 %b monotonic
  ret i8 %1
}

define i16 @atomicrmw_xor_i16_monotonic(ptr %a, i16 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i16_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r5, $r5, 0
; CHECK-NEXT:    addi.d $r6, $zero, -4
; CHECK-NEXT:    and $r6, $r4, $r6
; CHECK-NEXT:    andi $r4, $r4, 3
; CHECK-NEXT:    slli.w $r7, $r4, 3
; CHECK-NEXT:    lu12i.w $r4, 15
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    sll.w $r8, $r4, $r7
; CHECK-NEXT:    nor $r9, $zero, $r8
; CHECK-NEXT:    sll.w $r5, $r5, $r7
; CHECK-NEXT:  .LBB157_1: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ll.w $r10, $r6, 0
; CHECK-NEXT:    xor $r11, $r10, $r5
; CHECK-NEXT:    and $r11, $r11, $r8
; CHECK-NEXT:    and $r12, $r10, $r9
; CHECK-NEXT:    or $r12, $r12, $r11
; CHECK-NEXT:    sc.w $r12, $r6, 0
; CHECK-NEXT:    beq $r12, $zero, .LBB157_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    and $r4, $r10, $r8
; CHECK-NEXT:    srl.w $r4, $r4, $r7
; CHECK-NEXT:    ext.w.h $r4, $r4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i16 %b monotonic
  ret i16 %1
}

define i32 @atomicrmw_xor_i32_monotonic(ptr %a, i32 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i32_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli.w $r6, $r5, 0
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amxor_db.w $r5, $r6, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r5
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i32 %b monotonic
  ret i32 %1
}

define i64 @atomicrmw_xor_i64_monotonic(ptr %a, i64 %b) nounwind {
; CHECK-LABEL: atomicrmw_xor_i64_monotonic:
; CHECK:       # %bb.0:
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    amxor_db.d $r6, $r5, $r4, 0
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    move $r4, $r6
; CHECK-NEXT:    jr $ra
  %1 = atomicrmw xor ptr %a, i64 %b monotonic
  ret i64 %1
}
