; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch64 < %s | FileCheck %s --check-prefix=LA64

define void @fence_acquire() nounwind {
; LA64-LABEL: fence_acquire:
; LA64:       # %bb.0:
; LA64-NEXT:    dbar 20
; LA64-NEXT:    jr $ra
  fence acquire
  ret void
}

define void @fence_release() nounwind {
; LA64-LABEL: fence_release:
; LA64:       # %bb.0:
; LA64-NEXT:    dbar 18
; LA64-NEXT:    jr $ra
  fence release
  ret void
}

define void @fence_acq_rel() nounwind {
; LA64-LABEL: fence_acq_rel:
; LA64:       # %bb.0:
; LA64-NEXT:    dbar 16
; LA64-NEXT:    jr $ra
  fence acq_rel
  ret void
}

define void @fence_seq_cst() nounwind {
; LA64-LABEL: fence_seq_cst:
; LA64:       # %bb.0:
; LA64-NEXT:    dbar 16
; LA64-NEXT:    jr $ra
  fence seq_cst
  ret void
}
