; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch64 < %s | FileCheck %s

define void @fence_singlethread() {
; CHECK-LABEL: fence_singlethread:
; CHECK:       # %bb.0:
; CHECK-NEXT:    dbar 0
; CHECK-NEXT:    jr $ra
  fence syncscope("singlethread") seq_cst
  ret void
}
