; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=loongarch64 < %s | FileCheck %s
define i64 @li0000000000000000() {
; CHECK-LABEL: li0000000000000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.d $r4, $zero, 0
; CHECK-NEXT:    jr $ra
  ret i64 0
}

define i64 @li00000000000007ff() {
; CHECK-LABEL: li00000000000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.d $r4, $zero, 2047
; CHECK-NEXT:    jr $ra
  ret i64 2047
}

define i64 @li0000000000000800() {
; CHECK-LABEL: li0000000000000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    jr $ra
  ret i64 2048
}

define i64 @li0000000000000fff() {
; CHECK-LABEL: li0000000000000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    jr $ra
  ret i64 4095
}

define i64 @li000000007ffff000() {
; CHECK-LABEL: li000000007ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2147479552
}

define i64 @li000000007ffff7ff() {
; CHECK-LABEL: li000000007ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 2147481599
}

define i64 @li000000007ffff800() {
; CHECK-LABEL: li000000007ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    jr $ra
  ret i64 2147481600
}

define i64 @li000000007fffffff() {
; CHECK-LABEL: li000000007fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    jr $ra
  ret i64 2147483647
}

define i64 @li0000000080000000() {
; CHECK-LABEL: li0000000080000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2147483648
}

define i64 @li00000000800007ff() {
; CHECK-LABEL: li00000000800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2147485695
}

define i64 @li0000000080000800() {
; CHECK-LABEL: li0000000080000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2147485696
}

define i64 @li0000000080000fff() {
; CHECK-LABEL: li0000000080000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2147487743
}

define i64 @li00000000fffff000() {
; CHECK-LABEL: li00000000fffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4294963200
}

define i64 @li00000000fffff7ff() {
; CHECK-LABEL: li00000000fffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4294965247
}

define i64 @li00000000fffff800() {
; CHECK-LABEL: li00000000fffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4294965248
}

define i64 @li00000000ffffffff() {
; CHECK-LABEL: li00000000ffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4294967295
}

define i64 @li0007ffff00000000() {
; CHECK-LABEL: li0007ffff00000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 0
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251795518717952
}

define i64 @li0007ffff000007ff() {
; CHECK-LABEL: li0007ffff000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251795518719999
}

define i64 @li0007ffff00000800() {
; CHECK-LABEL: li0007ffff00000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251795518720000
}

define i64 @li0007ffff00000fff() {
; CHECK-LABEL: li0007ffff00000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251795518722047
}

define i64 @li0007ffff7ffff000() {
; CHECK-LABEL: li0007ffff7ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251797666197504
}

define i64 @li0007ffff7ffff7ff() {
; CHECK-LABEL: li0007ffff7ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251797666199551
}

define i64 @li0007ffff7ffff800() {
; CHECK-LABEL: li0007ffff7ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251797666199552
}

define i64 @li0007ffff7fffffff() {
; CHECK-LABEL: li0007ffff7fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251797666201599
}

define i64 @li0007ffff80000000() {
; CHECK-LABEL: li0007ffff80000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251797666201600
}

define i64 @li0007ffff800007ff() {
; CHECK-LABEL: li0007ffff800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251797666203647
}

define i64 @li0007ffff80000800() {
; CHECK-LABEL: li0007ffff80000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251797666203648
}

define i64 @li0007ffff80000fff() {
; CHECK-LABEL: li0007ffff80000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251797666205695
}

define i64 @li0007fffffffff000() {
; CHECK-LABEL: li0007fffffffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251799813681152
}

define i64 @li0007fffffffff7ff() {
; CHECK-LABEL: li0007fffffffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251799813683199
}

define i64 @li0007fffffffff800() {
; CHECK-LABEL: li0007fffffffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251799813683200
}

define i64 @li0007ffffffffffff() {
; CHECK-LABEL: li0007ffffffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    jr $ra
  ret i64 2251799813685247
}

define i64 @li0008000000000000() {
; CHECK-LABEL: li0008000000000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 0
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251799813685248
}

define i64 @li00080000000007ff() {
; CHECK-LABEL: li00080000000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251799813687295
}

define i64 @li0008000000000800() {
; CHECK-LABEL: li0008000000000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251799813687296
}

define i64 @li0008000000000fff() {
; CHECK-LABEL: li0008000000000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251799813689343
}

define i64 @li000800007ffff000() {
; CHECK-LABEL: li000800007ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251801961164800
}

define i64 @li000800007ffff7ff() {
; CHECK-LABEL: li000800007ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251801961166847
}

define i64 @li000800007ffff800() {
; CHECK-LABEL: li000800007ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251801961166848
}

define i64 @li000800007fffffff() {
; CHECK-LABEL: li000800007fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251801961168895
}

define i64 @li0008000080000000() {
; CHECK-LABEL: li0008000080000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251801961168896
}

define i64 @li00080000800007ff() {
; CHECK-LABEL: li00080000800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251801961170943
}

define i64 @li0008000080000800() {
; CHECK-LABEL: li0008000080000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251801961170944
}

define i64 @li0008000080000fff() {
; CHECK-LABEL: li0008000080000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251801961172991
}

define i64 @li00080000fffff000() {
; CHECK-LABEL: li00080000fffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251804108648448
}

define i64 @li00080000fffff7ff() {
; CHECK-LABEL: li00080000fffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251804108650495
}

define i64 @li00080000fffff800() {
; CHECK-LABEL: li00080000fffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251804108650496
}

define i64 @li00080000ffffffff() {
; CHECK-LABEL: li00080000ffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 2251804108652543
}

define i64 @li000fffff00000000() {
; CHECK-LABEL: li000fffff00000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 0
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503595332403200
}

define i64 @li000fffff000007ff() {
; CHECK-LABEL: li000fffff000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503595332405247
}

define i64 @li000fffff00000800() {
; CHECK-LABEL: li000fffff00000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503595332405248
}

define i64 @li000fffff00000fff() {
; CHECK-LABEL: li000fffff00000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503595332407295
}

define i64 @li000fffff7ffff000() {
; CHECK-LABEL: li000fffff7ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503597479882752
}

define i64 @li000fffff7ffff7ff() {
; CHECK-LABEL: li000fffff7ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503597479884799
}

define i64 @li000fffff7ffff800() {
; CHECK-LABEL: li000fffff7ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503597479884800
}

define i64 @li000fffff7fffffff() {
; CHECK-LABEL: li000fffff7fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503597479886847
}

define i64 @li000fffff80000000() {
; CHECK-LABEL: li000fffff80000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503597479886848
}

define i64 @li000fffff800007ff() {
; CHECK-LABEL: li000fffff800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503597479888895
}

define i64 @li000fffff80000800() {
; CHECK-LABEL: li000fffff80000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503597479888896
}

define i64 @li000fffff80000fff() {
; CHECK-LABEL: li000fffff80000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503597479890943
}

define i64 @li000ffffffffff000() {
; CHECK-LABEL: li000ffffffffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503599627366400
}

define i64 @li000ffffffffff7ff() {
; CHECK-LABEL: li000ffffffffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503599627368447
}

define i64 @li000ffffffffff800() {
; CHECK-LABEL: li000ffffffffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503599627368448
}

define i64 @li000fffffffffffff() {
; CHECK-LABEL: li000fffffffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    jr $ra
  ret i64 4503599627370495
}

define i64 @li7ff0000000000000() {
; CHECK-LABEL: li7ff0000000000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu52i.d $r4, $zero, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868437227405312
}

define i64 @li7ff00000000007ff() {
; CHECK-LABEL: li7ff00000000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868437227407359
}

define i64 @li7ff0000000000800() {
; CHECK-LABEL: li7ff0000000000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868437227407360
}

define i64 @li7ff0000000000fff() {
; CHECK-LABEL: li7ff0000000000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868437227409407
}

define i64 @li7ff000007ffff000() {
; CHECK-LABEL: li7ff000007ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868439374884864
}

define i64 @li7ff000007ffff7ff() {
; CHECK-LABEL: li7ff000007ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868439374886911
}

define i64 @li7ff000007ffff800() {
; CHECK-LABEL: li7ff000007ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868439374886912
}

define i64 @li7ff000007fffffff() {
; CHECK-LABEL: li7ff000007fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868439374888959
}

define i64 @li7ff0000080000000() {
; CHECK-LABEL: li7ff0000080000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868439374888960
}

define i64 @li7ff00000800007ff() {
; CHECK-LABEL: li7ff00000800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868439374891007
}

define i64 @li7ff0000080000800() {
; CHECK-LABEL: li7ff0000080000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868439374891008
}

define i64 @li7ff0000080000fff() {
; CHECK-LABEL: li7ff0000080000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868439374893055
}

define i64 @li7ff00000fffff000() {
; CHECK-LABEL: li7ff00000fffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868441522368512
}

define i64 @li7ff00000fffff7ff() {
; CHECK-LABEL: li7ff00000fffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868441522370559
}

define i64 @li7ff00000fffff800() {
; CHECK-LABEL: li7ff00000fffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868441522370560
}

define i64 @li7ff00000ffffffff() {
; CHECK-LABEL: li7ff00000ffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9218868441522372607
}

define i64 @li7ff7ffff00000000() {
; CHECK-LABEL: li7ff7ffff00000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 0
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120232746123264
}

define i64 @li7ff7ffff000007ff() {
; CHECK-LABEL: li7ff7ffff000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120232746125311
}

define i64 @li7ff7ffff00000800() {
; CHECK-LABEL: li7ff7ffff00000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120232746125312
}

define i64 @li7ff7ffff00000fff() {
; CHECK-LABEL: li7ff7ffff00000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120232746127359
}

define i64 @li7ff7ffff7ffff000() {
; CHECK-LABEL: li7ff7ffff7ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120234893602816
}

define i64 @li7ff7ffff7ffff7ff() {
; CHECK-LABEL: li7ff7ffff7ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120234893604863
}

define i64 @li7ff7ffff7ffff800() {
; CHECK-LABEL: li7ff7ffff7ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120234893604864
}

define i64 @li7ff7ffff7fffffff() {
; CHECK-LABEL: li7ff7ffff7fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120234893606911
}

define i64 @li7ff7ffff80000000() {
; CHECK-LABEL: li7ff7ffff80000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120234893606912
}

define i64 @li7ff7ffff800007ff() {
; CHECK-LABEL: li7ff7ffff800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120234893608959
}

define i64 @li7ff7ffff80000800() {
; CHECK-LABEL: li7ff7ffff80000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120234893608960
}

define i64 @li7ff7ffff80000fff() {
; CHECK-LABEL: li7ff7ffff80000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120234893611007
}

define i64 @li7ff7fffffffff000() {
; CHECK-LABEL: li7ff7fffffffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120237041086464
}

define i64 @li7ff7fffffffff7ff() {
; CHECK-LABEL: li7ff7fffffffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120237041088511
}

define i64 @li7ff7fffffffff800() {
; CHECK-LABEL: li7ff7fffffffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120237041088512
}

define i64 @li7ff7ffffffffffff() {
; CHECK-LABEL: li7ff7ffffffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120237041090559
}

define i64 @li7ff8000000000000() {
; CHECK-LABEL: li7ff8000000000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 0
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120237041090560
}

define i64 @li7ff80000000007ff() {
; CHECK-LABEL: li7ff80000000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120237041092607
}

define i64 @li7ff8000000000800() {
; CHECK-LABEL: li7ff8000000000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120237041092608
}

define i64 @li7ff8000000000fff() {
; CHECK-LABEL: li7ff8000000000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120237041094655
}

define i64 @li7ff800007ffff000() {
; CHECK-LABEL: li7ff800007ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120239188570112
}

define i64 @li7ff800007ffff7ff() {
; CHECK-LABEL: li7ff800007ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120239188572159
}

define i64 @li7ff800007ffff800() {
; CHECK-LABEL: li7ff800007ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120239188572160
}

define i64 @li7ff800007fffffff() {
; CHECK-LABEL: li7ff800007fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120239188574207
}

define i64 @li7ff8000080000000() {
; CHECK-LABEL: li7ff8000080000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120239188574208
}

define i64 @li7ff80000800007ff() {
; CHECK-LABEL: li7ff80000800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120239188576255
}

define i64 @li7ff8000080000800() {
; CHECK-LABEL: li7ff8000080000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120239188576256
}

define i64 @li7ff8000080000fff() {
; CHECK-LABEL: li7ff8000080000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120239188578303
}

define i64 @li7ff80000fffff000() {
; CHECK-LABEL: li7ff80000fffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120241336053760
}

define i64 @li7ff80000fffff7ff() {
; CHECK-LABEL: li7ff80000fffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120241336055807
}

define i64 @li7ff80000fffff800() {
; CHECK-LABEL: li7ff80000fffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120241336055808
}

define i64 @li7ff80000ffffffff() {
; CHECK-LABEL: li7ff80000ffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9221120241336057855
}

define i64 @li7fffffff00000000() {
; CHECK-LABEL: li7fffffff00000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 0
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372032559808512
}

define i64 @li7fffffff000007ff() {
; CHECK-LABEL: li7fffffff000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372032559810559
}

define i64 @li7fffffff00000800() {
; CHECK-LABEL: li7fffffff00000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372032559810560
}

define i64 @li7fffffff00000fff() {
; CHECK-LABEL: li7fffffff00000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372032559812607
}

define i64 @li7fffffff7ffff000() {
; CHECK-LABEL: li7fffffff7ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372034707288064
}

define i64 @li7fffffff7ffff7ff() {
; CHECK-LABEL: li7fffffff7ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372034707290111
}

define i64 @li7fffffff7ffff800() {
; CHECK-LABEL: li7fffffff7ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372034707290112
}

define i64 @li7fffffff7fffffff() {
; CHECK-LABEL: li7fffffff7fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372034707292159
}

define i64 @li7fffffff80000000() {
; CHECK-LABEL: li7fffffff80000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372034707292160
}

define i64 @li7fffffff800007ff() {
; CHECK-LABEL: li7fffffff800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372034707294207
}

define i64 @li7fffffff80000800() {
; CHECK-LABEL: li7fffffff80000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372034707294208
}

define i64 @li7fffffff80000fff() {
; CHECK-LABEL: li7fffffff80000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372034707296255
}

define i64 @li7ffffffffffff000() {
; CHECK-LABEL: li7ffffffffffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372036854771712
}

define i64 @li7ffffffffffff7ff() {
; CHECK-LABEL: li7ffffffffffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372036854773759
}

define i64 @li7ffffffffffff800() {
; CHECK-LABEL: li7ffffffffffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372036854773760
}

define i64 @li7fffffffffffffff() {
; CHECK-LABEL: li7fffffffffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 9223372036854775807
}

define i64 @li8000000000000000() {
; CHECK-LABEL: li8000000000000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu52i.d $r4, $zero, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372036854775808
}

define i64 @li80000000000007ff() {
; CHECK-LABEL: li80000000000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372036854773761
}

define i64 @li8000000000000800() {
; CHECK-LABEL: li8000000000000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372036854773760
}

define i64 @li8000000000000fff() {
; CHECK-LABEL: li8000000000000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372036854771713
}

define i64 @li800000007ffff000() {
; CHECK-LABEL: li800000007ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372034707296256
}

define i64 @li800000007ffff7ff() {
; CHECK-LABEL: li800000007ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372034707294209
}

define i64 @li800000007ffff800() {
; CHECK-LABEL: li800000007ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372034707294208
}

define i64 @li800000007fffffff() {
; CHECK-LABEL: li800000007fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372034707292161
}

define i64 @li8000000080000000() {
; CHECK-LABEL: li8000000080000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372034707292160
}

define i64 @li80000000800007ff() {
; CHECK-LABEL: li80000000800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372034707290113
}

define i64 @li8000000080000800() {
; CHECK-LABEL: li8000000080000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372034707290112
}

define i64 @li8000000080000fff() {
; CHECK-LABEL: li8000000080000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372034707288065
}

define i64 @li80000000fffff000() {
; CHECK-LABEL: li80000000fffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372032559812608
}

define i64 @li80000000fffff7ff() {
; CHECK-LABEL: li80000000fffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372032559810561
}

define i64 @li80000000fffff800() {
; CHECK-LABEL: li80000000fffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372032559810560
}

define i64 @li80000000ffffffff() {
; CHECK-LABEL: li80000000ffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9223372032559808513
}

define i64 @li8007ffff00000000() {
; CHECK-LABEL: li8007ffff00000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 0
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120241336057856
}

define i64 @li8007ffff000007ff() {
; CHECK-LABEL: li8007ffff000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120241336055809
}

define i64 @li8007ffff00000800() {
; CHECK-LABEL: li8007ffff00000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120241336055808
}

define i64 @li8007ffff00000fff() {
; CHECK-LABEL: li8007ffff00000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120241336053761
}

define i64 @li8007ffff7ffff000() {
; CHECK-LABEL: li8007ffff7ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120239188578304
}

define i64 @li8007ffff7ffff7ff() {
; CHECK-LABEL: li8007ffff7ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120239188576257
}

define i64 @li8007ffff7ffff800() {
; CHECK-LABEL: li8007ffff7ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120239188576256
}

define i64 @li8007ffff7fffffff() {
; CHECK-LABEL: li8007ffff7fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120239188574209
}

define i64 @li8007ffff80000000() {
; CHECK-LABEL: li8007ffff80000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120239188574208
}

define i64 @li8007ffff800007ff() {
; CHECK-LABEL: li8007ffff800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120239188572161
}

define i64 @li8007ffff80000800() {
; CHECK-LABEL: li8007ffff80000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120239188572160
}

define i64 @li8007ffff80000fff() {
; CHECK-LABEL: li8007ffff80000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120239188570113
}

define i64 @li8007fffffffff000() {
; CHECK-LABEL: li8007fffffffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120237041094656
}

define i64 @li8007fffffffff7ff() {
; CHECK-LABEL: li8007fffffffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120237041092609
}

define i64 @li8007fffffffff800() {
; CHECK-LABEL: li8007fffffffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120237041092608
}

define i64 @li8007ffffffffffff() {
; CHECK-LABEL: li8007ffffffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120237041090561
}

define i64 @li8008000000000000() {
; CHECK-LABEL: li8008000000000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 0
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120237041090560
}

define i64 @li80080000000007ff() {
; CHECK-LABEL: li80080000000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120237041088513
}

define i64 @li8008000000000800() {
; CHECK-LABEL: li8008000000000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120237041088512
}

define i64 @li8008000000000fff() {
; CHECK-LABEL: li8008000000000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120237041086465
}

define i64 @li800800007ffff000() {
; CHECK-LABEL: li800800007ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120234893611008
}

define i64 @li800800007ffff7ff() {
; CHECK-LABEL: li800800007ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120234893608961
}

define i64 @li800800007ffff800() {
; CHECK-LABEL: li800800007ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120234893608960
}

define i64 @li800800007fffffff() {
; CHECK-LABEL: li800800007fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120234893606913
}

define i64 @li8008000080000000() {
; CHECK-LABEL: li8008000080000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120234893606912
}

define i64 @li80080000800007ff() {
; CHECK-LABEL: li80080000800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120234893604865
}

define i64 @li8008000080000800() {
; CHECK-LABEL: li8008000080000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120234893604864
}

define i64 @li8008000080000fff() {
; CHECK-LABEL: li8008000080000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120234893602817
}

define i64 @li80080000fffff000() {
; CHECK-LABEL: li80080000fffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120232746127360
}

define i64 @li80080000fffff7ff() {
; CHECK-LABEL: li80080000fffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120232746125313
}

define i64 @li80080000fffff800() {
; CHECK-LABEL: li80080000fffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120232746125312
}

define i64 @li80080000ffffffff() {
; CHECK-LABEL: li80080000ffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9221120232746123265
}

define i64 @li800fffff00000000() {
; CHECK-LABEL: li800fffff00000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 0
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868441522372608
}

define i64 @li800fffff000007ff() {
; CHECK-LABEL: li800fffff000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868441522370561
}

define i64 @li800fffff00000800() {
; CHECK-LABEL: li800fffff00000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868441522370560
}

define i64 @li800fffff00000fff() {
; CHECK-LABEL: li800fffff00000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868441522368513
}

define i64 @li800fffff7ffff000() {
; CHECK-LABEL: li800fffff7ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868439374893056
}

define i64 @li800fffff7ffff7ff() {
; CHECK-LABEL: li800fffff7ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868439374891009
}

define i64 @li800fffff7ffff800() {
; CHECK-LABEL: li800fffff7ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868439374891008
}

define i64 @li800fffff7fffffff() {
; CHECK-LABEL: li800fffff7fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868439374888961
}

define i64 @li800fffff80000000() {
; CHECK-LABEL: li800fffff80000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868439374888960
}

define i64 @li800fffff800007ff() {
; CHECK-LABEL: li800fffff800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868439374886913
}

define i64 @li800fffff80000800() {
; CHECK-LABEL: li800fffff80000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868439374886912
}

define i64 @li800fffff80000fff() {
; CHECK-LABEL: li800fffff80000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868439374884865
}

define i64 @li800ffffffffff000() {
; CHECK-LABEL: li800ffffffffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868437227409408
}

define i64 @li800ffffffffff7ff() {
; CHECK-LABEL: li800ffffffffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868437227407361
}

define i64 @li800ffffffffff800() {
; CHECK-LABEL: li800ffffffffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868437227407360
}

define i64 @li800fffffffffffff() {
; CHECK-LABEL: li800fffffffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -9218868437227405313
}

define i64 @lifff0000000000000() {
; CHECK-LABEL: lifff0000000000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu52i.d $r4, $zero, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503599627370496
}

define i64 @lifff00000000007ff() {
; CHECK-LABEL: lifff00000000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503599627368449
}

define i64 @lifff0000000000800() {
; CHECK-LABEL: lifff0000000000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503599627368448
}

define i64 @lifff0000000000fff() {
; CHECK-LABEL: lifff0000000000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503599627366401
}

define i64 @lifff000007ffff000() {
; CHECK-LABEL: lifff000007ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503597479890944
}

define i64 @lifff000007ffff7ff() {
; CHECK-LABEL: lifff000007ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503597479888897
}

define i64 @lifff000007ffff800() {
; CHECK-LABEL: lifff000007ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503597479888896
}

define i64 @lifff000007fffffff() {
; CHECK-LABEL: lifff000007fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503597479886849
}

define i64 @lifff0000080000000() {
; CHECK-LABEL: lifff0000080000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503597479886848
}

define i64 @lifff00000800007ff() {
; CHECK-LABEL: lifff00000800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503597479884801
}

define i64 @lifff0000080000800() {
; CHECK-LABEL: lifff0000080000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503597479884800
}

define i64 @lifff0000080000fff() {
; CHECK-LABEL: lifff0000080000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503597479882753
}

define i64 @lifff00000fffff000() {
; CHECK-LABEL: lifff00000fffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503595332407296
}

define i64 @lifff00000fffff7ff() {
; CHECK-LABEL: lifff00000fffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503595332405249
}

define i64 @lifff00000fffff800() {
; CHECK-LABEL: lifff00000fffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503595332405248
}

define i64 @lifff00000ffffffff() {
; CHECK-LABEL: lifff00000ffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4503595332403201
}

define i64 @lifff7ffff00000000() {
; CHECK-LABEL: lifff7ffff00000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 0
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251804108652544
}

define i64 @lifff7ffff000007ff() {
; CHECK-LABEL: lifff7ffff000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251804108650497
}

define i64 @lifff7ffff00000800() {
; CHECK-LABEL: lifff7ffff00000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251804108650496
}

define i64 @lifff7ffff00000fff() {
; CHECK-LABEL: lifff7ffff00000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251804108648449
}

define i64 @lifff7ffff7ffff000() {
; CHECK-LABEL: lifff7ffff7ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251801961172992
}

define i64 @lifff7ffff7ffff7ff() {
; CHECK-LABEL: lifff7ffff7ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251801961170945
}

define i64 @lifff7ffff7ffff800() {
; CHECK-LABEL: lifff7ffff7ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251801961170944
}

define i64 @lifff7ffff7fffffff() {
; CHECK-LABEL: lifff7ffff7fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251801961168897
}

define i64 @lifff7ffff80000000() {
; CHECK-LABEL: lifff7ffff80000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251801961168896
}

define i64 @lifff7ffff800007ff() {
; CHECK-LABEL: lifff7ffff800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251801961166849
}

define i64 @lifff7ffff80000800() {
; CHECK-LABEL: lifff7ffff80000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251801961166848
}

define i64 @lifff7ffff80000fff() {
; CHECK-LABEL: lifff7ffff80000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251801961164801
}

define i64 @lifff7fffffffff000() {
; CHECK-LABEL: lifff7fffffffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251799813689344
}

define i64 @lifff7fffffffff7ff() {
; CHECK-LABEL: lifff7fffffffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251799813687297
}

define i64 @lifff7fffffffff800() {
; CHECK-LABEL: lifff7fffffffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251799813687296
}

define i64 @lifff7ffffffffffff() {
; CHECK-LABEL: lifff7ffffffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2251799813685249
}

define i64 @lifff8000000000000() {
; CHECK-LABEL: lifff8000000000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 0
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251799813685248
}

define i64 @lifff80000000007ff() {
; CHECK-LABEL: lifff80000000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251799813683201
}

define i64 @lifff8000000000800() {
; CHECK-LABEL: lifff8000000000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251799813683200
}

define i64 @lifff8000000000fff() {
; CHECK-LABEL: lifff8000000000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251799813681153
}

define i64 @lifff800007ffff000() {
; CHECK-LABEL: lifff800007ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251797666205696
}

define i64 @lifff800007ffff7ff() {
; CHECK-LABEL: lifff800007ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251797666203649
}

define i64 @lifff800007ffff800() {
; CHECK-LABEL: lifff800007ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251797666203648
}

define i64 @lifff800007fffffff() {
; CHECK-LABEL: lifff800007fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251797666201601
}

define i64 @lifff8000080000000() {
; CHECK-LABEL: lifff8000080000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251797666201600
}

define i64 @lifff80000800007ff() {
; CHECK-LABEL: lifff80000800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251797666199553
}

define i64 @lifff8000080000800() {
; CHECK-LABEL: lifff8000080000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251797666199552
}

define i64 @lifff8000080000fff() {
; CHECK-LABEL: lifff8000080000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251797666197505
}

define i64 @lifff80000fffff000() {
; CHECK-LABEL: lifff80000fffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251795518722048
}

define i64 @lifff80000fffff7ff() {
; CHECK-LABEL: lifff80000fffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251795518720001
}

define i64 @lifff80000fffff800() {
; CHECK-LABEL: lifff80000fffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251795518720000
}

define i64 @lifff80000ffffffff() {
; CHECK-LABEL: lifff80000ffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2251795518717953
}

define i64 @liffffffff00000000() {
; CHECK-LABEL: liffffffff00000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 0
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4294967296
}

define i64 @liffffffff000007ff() {
; CHECK-LABEL: liffffffff000007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2047
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4294965249
}

define i64 @liffffffff00000800() {
; CHECK-LABEL: liffffffff00000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4294965248
}

define i64 @liffffffff00000fff() {
; CHECK-LABEL: liffffffff00000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4294963201
}

define i64 @liffffffff7ffff000() {
; CHECK-LABEL: liffffffff7ffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2147487744
}

define i64 @liffffffff7ffff7ff() {
; CHECK-LABEL: liffffffff7ffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2147485697
}

define i64 @liffffffff7ffff800() {
; CHECK-LABEL: liffffffff7ffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2147485696
}

define i64 @liffffffff7fffffff() {
; CHECK-LABEL: liffffffff7fffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -2147483649
}

define i64 @liffffffff80000000() {
; CHECK-LABEL: liffffffff80000000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    jr $ra
  ret i64 -2147483648
}

define i64 @liffffffff800007ff() {
; CHECK-LABEL: liffffffff800007ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 -2147481601
}

define i64 @liffffffff80000800() {
; CHECK-LABEL: liffffffff80000800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    jr $ra
  ret i64 -2147481600
}

define i64 @liffffffff80000fff() {
; CHECK-LABEL: liffffffff80000fff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 4095
; CHECK-NEXT:    jr $ra
  ret i64 -2147479553
}

define i64 @lifffffffffffff000() {
; CHECK-LABEL: lifffffffffffff000:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    jr $ra
  ret i64 -4096
}

define i64 @lifffffffffffff7ff() {
; CHECK-LABEL: lifffffffffffff7ff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    jr $ra
  ret i64 -2049
}

define i64 @lifffffffffffff800() {
; CHECK-LABEL: lifffffffffffff800:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.d $r4, $zero, -2048
; CHECK-NEXT:    jr $ra
  ret i64 -2048
}

define i64 @liffffffffffffffff() {
; CHECK-LABEL: liffffffffffffffff:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.d $r4, $zero, -1
; CHECK-NEXT:    jr $ra
  ret i64 -1
}
