; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=loongarch64 -verify-machineinstrs -o - %s \
; RUN:   | FileCheck %s --check-prefix=STATIC
; RUN: llc -march=loongarch64 -verify-machineinstrs -relocation-model=pic --code-model=large -o - %s \
; RUN:   | FileCheck %s --check-prefix=LARGE

define void @test() nounwind {
; STATIC-LABEL: test:
; STATIC:       # %bb.0:
; STATIC-NEXT:    addi.d $sp, $sp, -16
; STATIC-NEXT:    st.d $ra, $sp, 8 # 8-byte Folded Spill
; STATIC-NEXT:    lu12i.w $ra, foo
; STATIC-NEXT:    ori $ra, $ra, foo
; STATIC-NEXT:    lu32i.d $ra, foo
; STATIC-NEXT:    lu52i.d $ra, $ra, foo
; STATIC-NEXT:    jirl $ra, $ra, 0
; STATIC-NEXT:    ld.d $ra, $sp, 8 # 8-byte Folded Reload
; STATIC-NEXT:    addi.d $sp, $sp, 16
; STATIC-NEXT:    jr $ra
;
; LARGE-LABEL: test:
; LARGE:       # %bb.0:
; LARGE-NEXT:    addi.d $sp, $sp, -16
; LARGE-NEXT:    st.d $ra, $sp, 8 # 8-byte Folded Spill
; LARGE-NEXT:    pcaddu18i $ra, foo
; LARGE-NEXT:    jirl $ra, $ra, foo
; LARGE-NEXT:    ld.d $ra, $sp, 8 # 8-byte Folded Reload
; LARGE-NEXT:    addi.d $sp, $sp, 16
; LARGE-NEXT:    jr $ra
  call void @foo() nounwind
  ret void
}

declare void @foo()
