; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=loongarch64 < %s | FileCheck %s

define void @test_trap() nounwind {
; CHECK-LABEL: test_trap:
; CHECK:       # %bb.0:
; CHECK-NEXT:    break 0
; CHECK-NEXT:    jr $ra
  call void @llvm.trap()
  ret void
}

declare void @llvm.trap()
