; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=loongarch64 -mattr=+lasx  < %s | FileCheck %s

define <4 x i64> @build_lasx0(<4 x i64> %a) {
; CHECK-LABEL: build_lasx0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -1
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    xvreplgr2vr.d $xr1, $r4
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
  %b = add <4 x i64> %a, <i64 4294967295, i64 4294967295, i64 4294967295, i64 4294967295>
  ret <4 x i64> %b
}

define <4 x i64> @build_lasx1(<4 x i64> %a) {
; CHECK-LABEL: build_lasx1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu52i.d $r4, $zero, 2047
; CHECK-NEXT:    xvreplgr2vr.d $xr1, $r4
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
  %b = add <4 x i64> %a, <i64 9218868437227405312, i64 9218868437227405312, i64 9218868437227405312, i64 9218868437227405312>
  ret <4 x i64> %b
}

define <4 x i64> @build_lasx2(<4 x i64> %a) {
; CHECK-LABEL: build_lasx2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 2048
; CHECK-NEXT:    lu32i.d $r4, 524287
; CHECK-NEXT:    xvreplgr2vr.d $xr1, $r4
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
  %b = add <4 x i64> %a, <i64 2251795518720000, i64 2251795518720000, i64 2251795518720000, i64 2251795518720000>
  ret <4 x i64> %b
}

define <4 x i64> @build_lasx3(<4 x i64> %a) {
; CHECK-LABEL: build_lasx3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu52i.d $r4, $r4, -1
; CHECK-NEXT:    xvreplgr2vr.d $xr1, $r4
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
  %b = add <4 x i64> %a, <i64 -4503599627366401, i64 -4503599627366401, i64 -4503599627366401, i64 -4503599627366401>
  ret <4 x i64> %b
}

define <4 x i64> @build_lasx4(<4 x i64> %a) {
; CHECK-LABEL: build_lasx4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ori $r4, $zero, 4095
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    xvreplgr2vr.d $xr1, $r4
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
  %b = add <4 x i64> %a, <i64 2251799813689343, i64 2251799813689343, i64 2251799813689343, i64 2251799813689343>
  ret <4 x i64> %b
}

define <4 x i64> @build_lasx5(<4 x i64> %a) {
; CHECK-LABEL: build_lasx5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    xvreplgr2vr.d $xr1, $r4
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
  %b = add <4 x i64> %a, <i64 4294965248, i64 4294965248, i64 4294965248, i64 4294965248>
  ret <4 x i64> %b
}

define <4 x i64> @build_lasx6(<4 x i64> %a) {
; CHECK-LABEL: build_lasx6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    xvreplgr2vr.d $xr1, $r4
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
  %b = add <4 x i64> %a, <i64 4503599627368448, i64 4503599627368448, i64 4503599627368448, i64 4503599627368448>
  ret <4 x i64> %b
}

define <4 x i64> @build_lasx7(<4 x i64> %a) {
; CHECK-LABEL: build_lasx7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.w $r4, $zero, -2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    xvreplgr2vr.d $xr1, $r4
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
  %b = add <4 x i64> %a, <i64 2251804108650496, i64 2251804108650496, i64 2251804108650496, i64 2251804108650496>
  ret <4 x i64> %b
}

define <4 x i64> @build_lasx8(<4 x i64> %a) {
; CHECK-LABEL: build_lasx8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    xvreplgr2vr.d $xr1, $r4
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
  %b = add <4 x i64> %a, <i64 2147483648, i64 2147483648, i64 2147483648, i64 2147483648>
  ret <4 x i64> %b
}

define <4 x i64> @build_lasx9(<4 x i64> %a) {
; CHECK-LABEL: build_lasx9:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -1
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    xvreplgr2vr.d $xr1, $r4
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
  %b = add <4 x i64> %a, <i64 4503599627366400, i64 4503599627366400, i64 4503599627366400, i64 4503599627366400>
  ret <4 x i64> %b
}

define <4 x i64> @build_lasx10(<4 x i64> %a) {
; CHECK-LABEL: build_lasx10:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    lu32i.d $r4, 0
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    xvreplgr2vr.d $xr1, $r4
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
  %b = add <4 x i64> %a, <i64 9218868439374888960, i64 9218868439374888960, i64 9218868439374888960, i64 9218868439374888960>
  ret <4 x i64> %b
}

define <4 x i64> @build_lasx11(<4 x i64> %a) {
; CHECK-LABEL: build_lasx11:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, 524287
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, -1
; CHECK-NEXT:    xvreplgr2vr.d $xr1, $r4
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
  %b = add <4 x i64> %a, <i64 -2147485696, i64 -2147485696, i64 -2147485696, i64 -2147485696>
  ret <4 x i64> %b
}

define <4 x i64> @build_lasx12(<4 x i64> %a) {
; CHECK-LABEL: build_lasx12:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2047
; CHECK-NEXT:    lu52i.d $r4, $r4, 2047
; CHECK-NEXT:    xvreplgr2vr.d $xr1, $r4
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
  %b = add <4 x i64> %a, <i64 9223372034707294207, i64 9223372034707294207, i64 9223372034707294207, i64 9223372034707294207>
  ret <4 x i64> %b
}

define <4 x i64> @build_lasx13(<4 x i64> %a) {
; CHECK-LABEL: build_lasx13:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lu12i.w $r4, -524288
; CHECK-NEXT:    ori $r4, $r4, 2048
; CHECK-NEXT:    lu32i.d $r4, -524288
; CHECK-NEXT:    lu52i.d $r4, $r4, 0
; CHECK-NEXT:    xvreplgr2vr.d $xr1, $r4
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    jr $ra
  %b = add <4 x i64> %a, <i64 2251801961170944, i64 2251801961170944, i64 2251801961170944, i64 2251801961170944>
  ret <4 x i64> %b
}
