; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=loongarch64 -mattr=+lasx  < %s | FileCheck %s

define <16 x i16> @lasxH(<16 x i16> %d, <8 x i16> %s1) {
; CHECK-LABEL: lasxH:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    # kill: def $vr1 killed $vr1 def $xr1
; CHECK-NEXT:    xvpermi.q $xr0, $xr1, 48
; CHECK-NEXT:    jr $ra
entry:
  %r1 = shufflevector <8 x i16> %s1, <8 x i16> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
  %r2 = shufflevector <16 x i16> %r1, <16 x i16> %d, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <16 x i16> %r2
}

define <8 x i32> @lasxW(<8 x i32> %d, <4 x i32> %s1) {
; CHECK-LABEL: lasxW:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    # kill: def $vr1 killed $vr1 def $xr1
; CHECK-NEXT:    xvpermi.q $xr0, $xr1, 48
; CHECK-NEXT:    jr $ra
entry:
  %r1 = shufflevector <4 x i32> %s1, <4 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 undef, i32 undef, i32 undef, i32 undef>
  %r2 = shufflevector <8 x i32> %r1, <8 x i32> %d, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
  ret <8 x i32> %r2
}

define <4 x i64> @lasxD(<4 x i64> %d, <2 x i64> %s1) {
; CHECK-LABEL: lasxD:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    # kill: def $vr1 killed $vr1 def $xr1
; CHECK-NEXT:    xvpermi.q $xr0, $xr1, 48
; CHECK-NEXT:    jr $ra
entry:
  %r1 = shufflevector <2 x i64> %s1, <2 x i64> poison, <4 x i32> <i32 0, i32 1, i32 undef, i32 undef>
  %r2 = shufflevector <4 x i64> %r1, <4 x i64> %d, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
  ret <4 x i64> %r2
}
