; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=loongarch64 -mattr=+lasx  < %s | FileCheck %s

define <4 x i64> @shuffle_v4i64_1032(<4 x i64> %vj, <4 x i64> %vk) {
; CHECK-LABEL: shuffle_v4i64_1032:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvpickve2gr.d $r4, $xr0, 2
; CHECK-NEXT:    xvpickve2gr.d $r5, $xr0, 3
; CHECK-NEXT:    xvpickve2gr.d $r6, $xr0, 0
; CHECK-NEXT:    xvpickve2gr.d $r7, $xr0, 1
; CHECK-NEXT:    xvinsgr2vr.d $xr0, $r7, 0
; CHECK-NEXT:    xvinsgr2vr.d $xr0, $r6, 1
; CHECK-NEXT:    xvinsgr2vr.d $xr0, $r5, 2
; CHECK-NEXT:    xvinsgr2vr.d $xr0, $r4, 3
; CHECK-NEXT:    jr $ra
entry:
  %vd = shufflevector <4 x i64> %vj, <4 x i64> %vk, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
  ret <4 x i64> %vd
}
