; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=loongarch64 -mattr=+lasx  < %s | FileCheck %s

define <4 x i64> @mul(<4 x i64> %a, <8 x i32> %m, <8 x i32> %n) {
; CHECK-LABEL: mul:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvhaddw.d.w $xr0, $xr1, $xr2
; CHECK-NEXT:    jr $ra
entry:
  %0 = shufflevector <8 x i32> %n, <8 x i32> undef, <2 x i32> <i32 0, i32 2>
  %1 = shufflevector <8 x i32> %m, <8 x i32> undef, <2 x i32> <i32 1, i32 3>
  %2 = add nsw <2 x i32> %0, %1
  %3 = sext <2 x i32> %2 to <2 x i64>
  %4 = shufflevector <8 x i32> %n, <8 x i32> undef, <2 x i32> <i32 4, i32 6>
  %5 = shufflevector <8 x i32> %m, <8 x i32> undef, <2 x i32> <i32 5, i32 7>
  %6 = add nsw <2 x i32> %4, %5
  %7 = sext <2 x i32> %6 to <2 x i64>
  %vecins16 = shufflevector <2 x i64> %3, <2 x i64> %7, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i64> %vecins16
}

