; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=loongarch64 -mattr=+lasx  < %s | FileCheck %s

define <32 x i8> @xvilvhb(<32 x i8> %vj, <32 x i8> %vk) {
; CHECK-LABEL: xvilvhb:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvilvh.b $xr0, $xr1, $xr0
; CHECK-NEXT:    jr $ra
entry:
  %vd = shufflevector <32 x i8> %vj, <32 x i8> %vk, <32 x i32> <i32 8, i32 40, i32 9, i32 41, i32 10, i32 42, i32 11, i32 43, i32 12, i32 44, i32 13, i32 45, i32 14, i32 46, i32 15, i32 47, i32 24, i32 56, i32 25, i32 57, i32 26, i32 58, i32 27, i32 59, i32 28, i32 60, i32 29, i32 61, i32 30, i32 62, i32 31, i32 63>
  ret <32 x i8> %vd
}

define <16 x i16> @xvilvhh(<16 x i16> %vj, <16 x i16> %vk) {
; CHECK-LABEL: xvilvhh:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvilvh.h $xr0, $xr1, $xr0
; CHECK-NEXT:    jr $ra
entry:
  %vd = shufflevector <16 x i16> %vj, <16 x i16> %vk, <16 x i32> <i32 4, i32 20, i32 5, i32 21, i32 6, i32 22, i32 7, i32 23, i32 12, i32 28, i32 13, i32 29, i32 14, i32 30, i32 15, i32 31>
  ret <16 x i16> %vd
}

define <8 x i32> @xvilvhw(<8 x i32> %vj, <8 x i32> %vk) {
; CHECK-LABEL: xvilvhw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvilvh.w $xr0, $xr1, $xr0
; CHECK-NEXT:    jr $ra
entry:
  %vd = shufflevector <8 x i32> %vj, <8 x i32> %vk, <8 x i32> <i32 2, i32 10, i32 3, i32 11, i32 6, i32 14, i32 7, i32 15>
  ret <8 x i32> %vd
}
